# Generated by Django 3.0.7 on 2020-06-22 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200621_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdetails',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.PersonalDetails'),
            preserve_default=False,
        ),
    ]
