# Generated by Django 3.0.7 on 2020-06-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_academicdetails_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicDetails',
        ),
    ]
