# Generated by Django 3.0.7 on 2020-06-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200621_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='Age',
            field=models.IntegerField(default=0, verbose_name='What is your Age ?'),
        ),
    ]
