# Generated by Django 3.0.7 on 2020-06-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200621_2357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='AcademicDetails',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='PersonalDetails',
        ),
    ]
