# Generated by Django 3.0.7 on 2020-06-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200621_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdetails',
            name='UGperc',
            field=models.IntegerField(default=0, verbose_name='UnderGrad Percentage'),
        ),
    ]
