# Generated by Django 3.0.7 on 2020-06-22 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200622_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdetails',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.PersonalDetails'),
        ),
    ]
