# Generated by Django 3.0.7 on 2020-06-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_academicdetails_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicdetails',
            old_name='votes',
            new_name='UGperc',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='votes',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='Age',
            field=models.IntegerField(default=0, verbose_name='What is your Age ?'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='Name',
            field=models.CharField(default='Junk', max_length=50, verbose_name='Full Name'),
        ),
    ]
