# Generated by Django 3.0.7 on 2020-06-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='', max_length=20)),
                ('overview', models.TextField(default='', max_length=300)),
                ('details', models.TextField(default='', max_length=300)),
                ('date', models.DateField(default='')),
                ('rating', models.IntegerField(default=0, max_length=300)),
            ],
        ),
    ]
