# Generated by Django 3.0.7 on 2020-06-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldata',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='traveldata',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
