# Generated by Django 3.0.7 on 2020-06-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20200622_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldata',
            name='img',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
