# Generated by Django 3.0.7 on 2020-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_traveldata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldata',
            name='img',
            field=models.ImageField(default='', upload_to='travel'),
        ),
    ]
